package vista;

import conexion.Conexion;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;


public class InterGraficaVentas extends javax.swing.JInternalFrame {

    ArrayList<Integer> listaCantidad = new ArrayList<>();
    ArrayList<String> listaFechas = new ArrayList<>();
    int cantidadResultados = 0;
    String[] vector_fechaVenta;
    int[] vector_estatus_cantidad;

    //Constructor
    public InterGraficaVentas() {
        initComponents();
        this.setSize(new Dimension(550, 650));
        this.setTitle("Historial de Ventas");
        this.MetodoContador();
        vector_fechaVenta = new String[cantidadResultados];
        vector_estatus_cantidad = new int[cantidadResultados];
        this.MetodoAlmacenaDatos();

    }

    //Metodo para determinar la cantidad de resultados a graficar
    private int MetodoContador() {
        try {

            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement(
                    "select fechaVenta, count(fechaVenta) as Ventas from tb_cabecera_venta "
                    + "where fechaVenta BETWEEN '" + InterGraficas.fecha_inicio + "' and '" + InterGraficas.fecha_fin + "' group by fechaVenta;");
            ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                cantidadResultados++;
            }
            cn.close();

        } catch (SQLException e) {
            System.out.println("Error en: " + e);
        }
        return cantidadResultados;
    }

    //Metodo para almacenar en las listas los datos a graficar
    private void MetodoAlmacenaDatos() {
    try {
        Connection cn = Conexion.conectar();
        PreparedStatement pst = cn.prepareStatement(
                "select fechaVenta, count(fechaVenta) as Ventas from tb_cabecera_venta "
                + "where fechaVenta BETWEEN '" + InterGraficas.fecha_inicio + "' and '" + InterGraficas.fecha_fin + "' group by fechaVenta;");
        ResultSet rs = pst.executeQuery();
        int contador = 0;
        while (rs.next()) {
            vector_fechaVenta[contador] = rs.getString("fechaVenta");
            listaFechas.add(vector_fechaVenta[contador]);
            vector_estatus_cantidad[contador] = rs.getInt("Ventas");
            listaCantidad.add(vector_estatus_cantidad[contador]);
            
            // Verifica que los datos estén siendo almacenados correctamente
            System.out.println("Fecha: " + vector_fechaVenta[contador] + " Cantidad: " + vector_estatus_cantidad[contador]);

            contador++;
        }
        cn.close();
    } catch (SQLException e) {
        System.out.println("Error en: " + e);
    }
}


    //Metodo para dterminar cual es el dia de mahyor cantidad de ventas
    public int MetodoMayorVenta(ArrayList<Integer> listaCantidad) {
        int mayor = 0;
        for (int i = 0; i < listaCantidad.size(); i++) {
            if (listaCantidad.get(i) > mayor) {
                mayor = listaCantidad.get(i);
            }
        }
        return mayor;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Seleccione fechas para Graficar");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 330, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    //metodo que dibuja graficas
   @Override
public void paint(Graphics g) {
    super.paint(g);

    int mayorVenta = MetodoMayorVenta(listaCantidad);  // Asegúrate de que esta función devuelve el mayor valor
    int largo_NuevoIngreso;
    int parametro1 = 133;    // Posición de la etiqueta "Cantidad"
    int parametroFecha = 118;  // Posición de la etiqueta "Fecha"
    int parametro3 = 100;    // Posición de las barras

    for (int i = 0; i < listaCantidad.size(); i++) {
        // Calcular la longitud de la barra proporcional
        largo_NuevoIngreso = listaCantidad.get(i) * 400 / mayorVenta;

        // Cambiar color según la barra
        if (i == 0) {
            g.setColor(new Color(140, 0, 75));  // Morado
        } else if (i == 1) {
            g.setColor(new Color(255, 0, 0));  // Rojo
        } else if (i == 2) {
            g.setColor(new Color(0, 0, 0));    // Negro
        } else {
            g.setColor(new Color(0, 85, 0));   // Verde
        }

        // Dibujar las barras
        g.fillRect(100, parametro3, largo_NuevoIngreso, 40);

        // Dibujar las etiquetas de fecha y cantidad
        g.setColor(Color.BLACK);
        g.drawString(listaFechas.get(i), 10, parametroFecha);
        g.drawString("Cantidad: " + listaCantidad.get(i), 10, parametro1);

        // Ajustar las posiciones para las siguientes barras
        parametro1 += 50;
        parametroFecha += 50;
        parametro3 += 50;
    }
    this.repaint();  // Esto asegura que el método paint se ejecute
}

}
